# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   # push:
#   #   branches: [ "main" ]
#   # pull_request:
#   #   branches: [ "main" ]
#   #   types:
#   #   - opened
#   #   - edited
#   #   - synchronize
#   #   - reopened
#   pull_request_review_comment:
#     types: [created]
#   # issue_comment:
#   #   types: [created]
#     # branches:
#     # - main

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     # if: github.event.issue.pull_request
#     # # if: github.event.review.state == 'approved'

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v4
#       - run: echo ${{ github.job }}

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.



name: "Deploy on Comment"

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    name: Deploy
    # Only run if it#s a PR and the comment contains /deploy
    # if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest

    steps:
      - name: Get branch of PR
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.












